name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab=3
  - numpy=1.24
  - scipy=1.10
  - bokeh=2.4
  - dask=2023.1.0
  - dask-labextension
  - distributed=2023.1.0
  - matplotlib
  - pandas=1.5
  - pip
  - python-graphviz
  - ipycytoscape
  - pyarrow
  - s3fs
  - zarr
  - pooch
  - xarray
  - mamba
