name: Fastapi-CI-Actions

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out git repository.'
        uses: actions/checkout@v2

      - name: 'Setup python env.'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 'Install python dependencies.'
        run: pip install fastapi pytest

      - name: 'Test with pytest run'
        run: pytest 